return {
    -- "neovim/nvim-lspconfig",
  --   dependencies = {
  --     {
  --       "folke/neoconf.nvim",
  --       opts = function()
  --         local global_settings, file_found
  --         local _, depth = vim.fn.stdpath("config"):gsub("/", "")
  --         for _, dir in ipairs(astronvim.supported_configs) do
  --           dir = dir .. "/lua/user"
  --           if vim.fn.isdirectory(dir) == 1 then
  --             local path = dir .. "/neoconf.json"
  --             if vim.fn.filereadable(path) == 1 then
  --               file_found = true
  --               global_settings = path
  --             elseif not file_found then
  --               global_settings = path
  --             end
  --           end
  --         end
  --         return { global_settings = global_settings and string.rep("../", depth):sub(1, -2) .. global_settings }
  --       end,
  --     },
  -- }
}
